server:
  port: 9000
  servlet:
    context-path: /gateway-test

spring:
  application:
    name: gateway
    web-application-type=reactive:
  cloud:
    nacos:
      discovery:
        enabled: true     # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        server-addr: 127.0.0.1:8848   # Nacos 服务器地址
        namespace: 87b914fd-4d41-456c-8bd3-3725272eebba

    # 静态路由
    gateway:
      routes:
        - id: user-service      # 路由的ID
          uri: http://localhost:7000   # 匹配后路由地址
          predicates:         # 断言, 路径相匹配的进行路由
            - Path=/user/**
          filters:
            - PrefixPath=/user-service-test

        - id: nacos-client
          uri: http://localhost:8000
          predicates:
            - Path=/nacos-client/**
          filters:
            - PrefixPath=/nacos-client-test

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true  # 因为将来会引入很多依赖, 难免有重名的 bean

# 这个地方独立配置, 是网关的数据, 代码 GatewayConfig.java 中读取被监听
nacos:
  gateway:
    route:
      config:
        data-id: gateway-router
        group: test
